[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "forge-std/=lib/forge-std/src/",
  "@hashgraph/smart-contracts/=lib/hedera-smart-contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
]

# Add this section for Hedera testnet
[rpc_endpoints]
testnet = "${HEDERA_RPC_URL}"

[lint]
exclude_lints = ["unaliased-plain-import"]